.Dd $Mdocdate$
.Dt DYNDNSD.CONF 5
.Os
.Sh NAME
.Nm dyndnsd.conf
.Nd Dynamic DNS daemon configuration file
.Sh DESCRIPTION
The
.Xr dyndnsd 8
daemon is a generic dynamic-DNS client.
.Nm
is the configuration file for this daemon.
.Ss COMMENTS
Comments begin with 
.Sq #
and continue to the end of the line.
.Ss STATEMENTS
.Bl -tag -width Ds
.It Sy domain Ar fqdn
This statement identifies a DNS domain,
.Ar fqdn .
This statement may be placed, without limit, within
.Sy interface
statements only.
.It Sy interface Ar name Sy { No ... Sy }
This statement identifies a network interface to monitor for IPv4-address changes. It's single argument,
.Ar name ,
is the name of the network interface to monitor. At least one
.Sy interface
statement is required.
.It Sy run Ar command
This statement defines the shell command to execute when a monitored-interface's IPv4-address changes.
.Pp
This statement takes a single, newline-delimited argument:
.Ar command ,
the shell command to execute, which will be passed verbatim to
.Em $SHELL
(or
.Pa /bin/sh
if
.Em $SHELL
is undefined).
.El
.Ss ENVIRONMENT VARIABLES
.Bl -tag -width Ds
.It Ev DYNDNSD_IPADDR
Contains the new IPv4 address.
.It Ev DYNDNSD_DOMAIN
.It Ev DYNDNSD_FQDN
.It Ev DYNDNSD_HOSTNAME
.It Ev DYNDNSD_INTERFACE
Contains the name of the monitored interface.
.It Ev DYNDNSD_TLD
.El
.Sh FILES
.Bl -tag -width "/etc/dyndnsd.conf" -compact
.It Pa /etc/dyndnsd.conf
.Xr dyndnsd 8
configuration file.
.El
.Sh EXAMPLES
.Bd -literal -offset Ds
run curl https://www.duckdns.org/update?domains=${DYNDNSD_FQDN}&token=secret&ip=${DYNDNSD_IPADDR}

interface em0 {
    domain www.example.com
}

interface em1 {
    domain ftp.example.com
}

.Ed
.Sh SEE ALSO
.Xr dyndnsd 8
.Sh AUTHORS
.An Mario Campos Aq Mt mario@mariocampos.io
