.Dd $Mdocdate$
.Dt DYNDNSD.CONF 5
.Os
.Sh NAME
.Nm dyndnsd.conf
.Nd Dynamic DNS Daemon configuration file
.Sh DESCRIPTION
The 
.Nm
configuration defines the entire configuration of
.Xr dyndnsd 8
, including the network interfaces to watch, the domain names to update, and the HTTP update APIs of your DNS provider(s).

Comments begin with 
.Sq #
and continue to the end of the line.

User input must be double-quoted if it contains whitespace ([ \\n\\t]). Otherwise, the double-quotes are optional.
.Ss interface Em string
.Ss domain Em string
.Ss update Em string
.Ss user Em string
.Ss group Em string
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/dyndnsd.conf
This is the default configuration file.
.El
.Sh EXAMPLES
The configuration below defines one network interface to watch and one domain name to update:
.Bd -literal -offset Ds
interface em0 {
    update https://namecheap.com
    domain example.com
}
.Ed

The following example illustrates a slightly-more complicated configuration:

.Bd -literal -offset Ds
interface em0 {
    domain www.example.com {
        update https://user2:secret@easydns.com/api/dyndns.php
    }
    domain www.example.org {
        update https://myuser:mypass@namecheap.com/api
    }
}
.Ed
.Sh SEE ALSO
.Xr dyndnsd 8
.Sh AUTHORS
.An Mario Campos Aq Mt mario@mariocampos.io
