.Dd $Mdocdate$
.Dt DYNDNSD 8
.Os
.Sh NAME
.Nm dyndnsd
.Nd Dynamic DNS daemon
.Sh SYNOPSIS
.Nm 
.Op Fl dhnv
.Op Fl f Ar file
.Sh DESCRIPTION
The
.Nm
daemon is a generic dynamic-DNS client. It will execute a given shell command when the IPv4 address of a monitored interface changes.
.Pp
If
.Nm
is executed as root, then it will drop its privilege to the user/group configured at compile-time.
.Pp
Upon receiving
.Dv SIGHUP ,
.Nm
reloads the configuration file.
.Ss OPTIONS 
.Bl -tag -width Ds
.It Fl d
Do not daemonize and log to stdout.
.It Fl f Ar file
Specify an alternate location,
.Ar file ,
for the configuration file.
.It Fl h
Print usage.
.It Fl n
Config-test mode. Validate the configuration file, then terminate.
.It Fl v
Print version number.
.El
.Sh FILES
.Bl -tag -width "/etc/dyndnsd.conf" -compact
.It Pa /etc/dyndnsd.conf
.Nm
configuration file
.El
.Sh EXIT STATUS
.Ex
.Sh SEE ALSO
.Xr dyndnsd.conf 5
.Sh AUTHORS
.An Mario Campos Aq Mt mario@mariocampos.io
