.Dd $Mdocdate$
.Dt DYNDNSD 8
.Os
.Sh NAME
.Nm dyndnsd
.Nd Dynamic DNS Daemon
.Sh SYNOPSIS
.Nm 
.Op Fl dhnv
.Op Fl f Ar file
.Sh DESCRIPTION
The
.Nm
daemon is a generic Dynamic-DNS client. That is, in order to dynamically update the public IP address of a domain's A record,
.Nm
will send an HTTP(S) GET request to the configured DNS provider if the configured network interface's IP address has changed.
.Ss OPTIONS 
.Bl -tag -width Ds
.It Fl d
Enable debug mode, which prevents
.Nm
from forking into the background, and prints
.Xr syslog 3
messages to standard error.
.It Fl f Ar file
Use
.Em file
as the configuration file.
.It Fl h
Print usage.
.It Fl n
Validate the configuration file, then terminate.
.It Fl v
Print version number.
.El
.Ss DROPPING PRIVILEGE
If
.Nm
is executed as a non-root user, then it will not attempt to change its process user and group.
.Pp
However, if
.Nm
is started as the root user, then it will drop privilege by first attempting to set its user/group to that which was specified in the configuration file. If no user/group was specified in the configuration file, then
.Nm
will attempt to set the user/group to the compile-time-configured user and group.
.Sh FILES
.Bl -tag
.It Pa /etc/dyndnsd.conf
Default configuration file
.El
.Sh EXIT STATUS
.Ex
.Sh SEE ALSO
.Xr dyndnsd.conf 5
.Sh AUTHORS
.An Mario Campos Aq Mt mario@mariocampos.io
