.Dd $Mdocdate$
.Dt DYNDNSD.CONF 5
.Os
.Sh NAME
.Nm dyndnsd.conf
.Nd Dynamic DNS daemon configuration file
.Sh DESCRIPTION
The
.Xr dyndnsd 8
daemon is a generic dynamic-DNS client.
.Nm
is the configuration file for this daemon.
.Pp
A
.Nm
configuration consists of a
.Ic run
statement and one or more
.Ic interface
statements.
.Ss QUOTING
Arguments may be double-quoted. However, note that arguments to
.Ic run
are passed to
.Em $SHELL
verbatim, including quotes.
.Pp
If an argument is a reserved word (such as
.Ic interface ,
.Ic domain , 
.Ic run Ns ),
then it must be double-quoted.
.Ss COMMENTS
Comments begin with 
.Sq #
and continue to the end of the line.
.Ss STATEMENTS
.Bl -tag -width Ds
.It Ic interface Ar name Brq ...
This statement identifies a network interface to monitor for IPv4-address changes. The argument
.Ar name
is the name of the network interface.
.Pp
This statement may be plural.
.Pp
The following statement(s) are valid inside of the scope of the
.Ic interface
statement (between the curly brackets):
.Bl -tag -width Ds
.It Ic domain Ar name
This statement identifies a DNS domain by the argument
.Ar name .
This statement may be plural.
.El
.It Ic run Ar command Oo Ar arg1 Oc Oo Ar arg2 Oc Op ...
This statement defines the
.Xr sh 1
command to execute when an interface's IPv4 address changes. The command does not block the execution of
.Xr dyndnsd 8 .
Nor does the command inherit its environment.
.Pp
This statement cannot be plural; there can be only one
.Ic run
statement.
.Pp
Line continuation is supported. The command line may be split into two (or more) lines by placing a backslash character at the end of the line that is to be split.
.Pp
These environment variables are made available to
.Ar command :
.Pp
.Bl -tag -width DYNDNSD_INTERFACE -compact
.It Ev DYNDNSD_IPADDR
The new IPv4 address.
.It Ev DYNDNSD_DOMAIN
The domain name currently in execution.
.It Ev DYNDNSD_INTERFACE
The name of the interface whose IPv4 address changed.
.El
.El
.Sh FILES
.Bl -tag -width "/etc/dyndnsd.conf" -compact
.It Pa /etc/dyndnsd.conf
.Xr dyndnsd 8
configuration file.
.El
.Sh EXAMPLES
.Bd -literal -offset indent
run curl "https://www.duckdns.org/update?token=secret&domains=${DYNDNSD_DOMAIN}&ip=${DYNDNSD_IPADDR}"

interface em0 {
    domain example.com
    domain www.example.com
}

interface "em1" {
    domain "ftp.example.com"
}

.Ed
.Sh SEE ALSO
.Xr dyndnsd 8
.Sh AUTHORS
.An Mario Campos Aq Mt mario.andres.campos@gmail.com
