name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
    - .github/workflows/c.yml
    - '**.[ch]'
    - Makefile
  pull_request:
    branches: [ master ]
    paths:
    - .github/workflows/c.yml
    - '**.[ch]'
    - Makefile

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        os: [ openbsd-latest ]
    steps:
    - name: Bootstrap ${{ matrix.os }}
      uses: mario-campos/emulate@v1
      with:
        operating-system: ${{ matrix.os }}
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/dyndnsd.git
    - name: Build
      run: cd dyndnsd && make
