name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ openbsd-6.9, freebsd-13.0, netbsd-9.2, dragonflybsd-5.2.0 ]
    steps:
    - name: Bootstrap ${{ matrix.os }}
      uses: mario-campos/emulate@main
      with:
        operating-system: ${{ matrix.os }}
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/dyndnsd.git
    - name: Build
      run: cd dyndnsd && make
