name: CppCheck

on:
  push:
    branches: [ master ]
    paths:
    - .github/workflows/cppcheck.yml
    - '**.[ch]'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install cppcheck
      run: sudo apt-get install -qq cppcheck
    - name: Run cppcheck
      run: >
        cppcheck
        --quiet
        --force
        --enable=all
        --error-exitcode=1
        .
